name: souffle
run-name: ${{github.actor}} is learning GitHub Actions

stages:
  - build
  - test
  - deploy

variables:
  RUST_BACKTRACE: full

before_script:
  - rustup update
  - cargo update

build:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/souffle

test:
  stage: test
  script:
    - cargo test

deploy_staging:
  stage: deploy
  script:
    - echo "Deploying to staging server..."
    # Здесь может быть скрипт для развертывания на тестовый сервер

deploy_production:
  stage: deploy
  script:
    - echo "Deploying to production server..."
    # Здесь может быть скрипт для развертывания на продакшн сервер
